#!/bin/bash
# Script para hacer deploy en Render desde línea de comandos

echo "================================"
echo "  DEPLOY A RENDER - mini-rrhh"
echo "================================"
echo ""
echo "Opción 1: Deploy Manual en Dashboard (MÁS FÁCIL)"
echo "----------------------------------------------"
echo "1. Ve a: https://dashboard.render.com"
echo "2. Loguéate con tu cuenta"
echo "3. Selecciona tu proyecto 'My project'"
echo "4. Encuentra el servicio 'mini-rrhh'"
echo "5. Haz clic en 'Clear build cache' (esquina superior derecha)"
echo "6. Haz clic en 'Manual Deploy' o 'Redeploy'"
echo "7. Espera 3-5 minutos a que complete"
echo ""
echo "Opción 2: Usar Render CLI"
echo "-------------------------"
echo "Ejecuta estos comandos:"
echo ""
echo "  npm install -g @render/cli"
echo "  render login"
echo "  render deploy --service mini-rrhh"
echo ""
echo "Opción 3: Con curl (si tienes API token)"
echo "------------------------------------------"
echo "render_api_key='tu_token_aqui'"
echo "service_id='srv_XXXXXXXXXXXXX'"
echo ""
echo "curl -X POST https://api.render.com/v1/services/\$service_id/deploys \\"
echo "  -H 'Authorization: Bearer \$render_api_key' \\"
echo "  -H 'Content-Type: application/json'"
echo ""
echo "================================"
echo "  LINKS ÚTILES"
echo "================================"
echo ""
echo "📊 Dashboard Render:    https://dashboard.render.com"
echo "📦 Tu Repositorio:      https://github.com/PEDROJOSEGGGG/Tarea-1-Componente-de-estadisticas"
echo "📋 Documentación:       https://render.com/docs"
echo ""
echo "¡El código está listo! Solo falta hacer el deploy en Render."
