import type { Employee } from '../types';

export const mockEmployees: Employee[] = [
    {
  id: 7,
  name: "Lucía Fernández",
  email: "lucia.fernandez@empresa.com",
  position: "Analista de Datos",
  Departament: "Tecnologia",
  salary: 9000,
  hireDate: "2020-11-12",
  status: "active",
  role: "employee",
},
{
  id: 8,
  name: "Miguel Torres",
  email: "miguel.torres@empresa.com",
  position: "Diseñador UX",
  Departament: "Tecnologia",
  salary: 7800,
  hireDate: "2021-05-03",
  status: "active",
  role: "employee",
},
{
  id: 9,
  name: "Sofía Ramírez",
  email: "sofia.ramirez@empresa.com",
  position: "Especialista en Reclutamiento",
  Departament: "Recursos Humanos",
  salary: 7000,
  hireDate: "2022-02-18",
  status: "active",
  role: "employee",
},
{
  id: 10,
  name: "Andrés Castillo",
  email: "andres.castillo@empresa.com",
  position: "Gerente de Finanzas",
  Departament: "Finanzas",
  salary: 16000,
  hireDate: "2017-09-25",
  status: "active",
  role: "admin",
},
{
  id: 11,
  name: "Paola Méndez",
  email: "paola.mendez@empresa.com",
  position: "Asistente Administrativa",
  Departament: "Recursos Humanos",
  salary: 6000,
  hireDate: "2023-01-10",
  status: "active",
  role: "employee",
},
{
  id: 12,
  name: "Javier Ruiz",
  email: "javier.ruiz@empresa.com",
  position: "Ingeniero Backend",
  Departament: "Tecnologia",
  salary: 11000,
  hireDate: "2019-04-14",
  status: "on_leave",
  role: "employee",
},
{
  id: 13,
  name: "Camila Soto",
  email: "camila.soto@empresa.com",
  position: "Analista Financiera",
  Departament: "Finanzas",
  salary: 8800,
  hireDate: "2020-08-07",
  status: "active",
  role: "employee",
},
{
  id: 14,
  name: "Diego Herrera",
  email: "diego.herrera@empresa.com",
  position: "Gerente de Proyectos",
  Departament: "Tecnologia",
  salary: 13500,
  hireDate: "2016-12-01",
  status: "active",
  role: "admin",
},
{
  id: 15,
  name: "Valeria Cruz",
  email: "valeria.cruz@empresa.com",
  position: "Especialista en Nómina",
  Departament: "Finanzas",
  salary: 7500,
  hireDate: "2021-09-30",
  status: "inactive",
  role: "employee",
},
{
  id: 16,
  name: "Fernando Díaz",
  email: "fernando.diaz@empresa.com",
  position: "Analista de Seguridad",
  Departament: "Tecnologia",
  salary: 12500,
  hireDate: "2018-03-22",
  status: "active",
  role: "employee",
},
{
  id: 17,
  name: "Gabriela Morales",
  email: "gabriela.morales@empresa.com",
  position: "Psicóloga Organizacional",
  Departament: "Recursos Humanos",
  salary: 9500,
  hireDate: "2020-06-11",
  status: "active",
  role: "employee",
},
{
  id: 18,
  name: "Ricardo Peña",
  email: "ricardo.pena@empresa.com",
  position: "Auditor Interno",
  Departament: "Finanzas",
  salary: 10000,
  hireDate: "2019-10-05",
  status: "active",
  role: "employee",
},
{
  id: 19,
  name: "Elena Vargas",
  email: "elena.vargas@empresa.com",
  position: "Especialista en Capacitación",
  Departament: "Recursos Humanos",
  salary: 7200,
  hireDate: "2022-04-19",
  status: "active",
  role: "employee",
},
{
  id: 20,
  name: "Tomás Navarro",
  email: "tomas.navarro@empresa.com",
  position: "Ingeniero DevOps",
  Departament: "Tecnologia",
  salary: 14000,
  hireDate: "2017-11-30",
  status: "active",
  role: "employee",
},
{
  id: 21,
  name: "Isabel Flores",
  email: "isabel.flores@empresa.com",
  position: "Analista de Presupuesto",
  Departament: "Finanzas",
  salary: 8700,
  hireDate: "2021-02-08",
  status: "on_leave",
  role: "employee",
}


]