import type { Employee } from '../types';

export const mockEmployees: Employee[] = [
    {
        id: 1,
        name: "Ana García",
        email: "ana.garcia@empresa.com",
        position: "Desarrolladora Frontend",
        department: "Tecnologia",
        salary: 8500,
        hireDate: "2022-03-15",
        status: "active",
        role: "employee",
avatarUrl: "https://th.bing.com/th/id/OIP.3vZkzvQkzXkV7gk8lFzFJwHaEK?w=310&h=200&c=7&rs=1&bgcl=ffffff&r=0&o=6&dpr=1.5&pid=Api",    },
    {
        id: 2,
        name: "Carlos Martínez",
        email: "carlos.martinez@empresa.com",
        position: "Gerente de RRHH",
        department: "Recursos Humanos",
        salary: 12000,
        hireDate: "2019-07-01",
        status: "active",
        role: "hr",
    },
    {
        id: 3,
        name: "María López",
        email: "maria.lopez@empresa.com",
        position: "Contadora Senior",
        department: "Finanzas",
        salary: 9500,
        hireDate: "2021-01-20",
        status: "on_leave",
        role: "employee",
    },
    {
        id: 4,
        name: "Roberto Silva",
        email: "roberto.silva@empresa.com",
        position: "Administrador del Sistema",
        department: "Tecnologia",
        salary: 15000,
        hireDate: "2018-05-10",
        status: "active",
        role: "admin",
    },

        {
        id: 5,
        name: "Cristiano Ronaldo",
        email: "cristiano.ronaldo@empresa.com",
        position: "Director de Tecnologia",
        department: "Tecnologia",
        salary: 15000,
        hireDate: "2018-05-10",
        status: "active",
        role: "admin",
    },

        {
        id: 6,
        name: "Zero two",
        email: "zero.two@empresa.com",
        position: "Auxiliar de Tecnologia",
        department: "Tecnologia",
        salary: 15000,
        hireDate: "2018-05-10",
        status: "inactive",
        role: "employee",
    },
];
