import type { Employee } from '../types';

export const mockEmployees: Employee[] = [
    {
        id: 1,
        name: "Ana García",
        email: "ana.garcia@empresa.com",
        position: "Desarrolladora Frontend",
        department: "Tecnologia",
        salary: 8500,
        hireDate: "2022-03-15",
        status: "active",
        role: "employee",
        
        avatarUrl: "https://th.bing.com/th/id/ODL.cce9ce0ec59ddfee5c45ef406d2ffcda?w=310&h=200&c=7&rs=1&bgcl=fffffc&r=0&o=6&dpr=1.5&pid=AlgoBlockDebug",
    },
    {
        id: 2,
        name: "Carlos Martínez",
        email: "carlos.martinez@empresa.com",
        position: "Gerente de RRHH",
        department: "Recursos Humanos",
        salary: 12000,
        hireDate: "2019-07-01",
        status: "active",
        role: "hr",
    },
    {
        id: 3,
        name: "María López",
        email: "maria.lopez@empresa.com",
        position: "Contadora Senior",
        department: "Finanzas",
        salary: 9500,
        hireDate: "2021-01-20",
        status: "on_leave",
        role: "employee",
    },
    {
        id: 4,
        name: "Roberto Silva",
        email: "roberto.silva@empresa.com",
        position: "Administrador del Sistema",
        department: "Tecnologia",
        salary: 15000,
        hireDate: "2018-05-10",
        status: "active",
        role: "admin",
    },
     {
        id: 5,
        name: "Bruno Leon",
        email: "bruno.leon@empresa.com",
        position: "Contador Senior",
        department: "Finanzas",
        salary: 8000,
        hireDate: "2021-07-01",
        status: "active",
        role: "employee",
    },
    {
        id: 6,
        name: "Duke Blanco",
        email: "duke.blanco@empresa.com",
        position: "Secretario de Finanzas",
        department: "Finanzas",
        salary: 12000,
        hireDate: "2018-09-01",
        status: "inactive",
        role: "employee",
    },
    {
  id: 7,
  name: "Lucía Fernández",
  email: "lucia.fernandez@empresa.com",
  position: "Analista de Datos",
  department: "Tecnologia",
  salary: 9000,
  hireDate: "2020-11-12",
  status: "active",
  role: "employee",
},
{
  id: 8,
  name: "Miguel Torres",
  email: "miguel.torres@empresa.com",
  position: "Diseñador UX",
  department: "Tecnologia",
  salary: 7800,
  hireDate: "2021-05-03",
  status: "active",
  role: "employee",
},
{
  id: 9,
  name: "Sofía Ramírez",
  email: "sofia.ramirez@empresa.com",
  position: "Especialista en Reclutamiento",
  department: "Recursos Humanos",
  salary: 7000,
  hireDate: "2022-02-18",
  status: "active",
  role: "employee",
},
{
  id: 10,
  name: "Andrés Castillo",
  email: "andres.castillo@empresa.com",
  position: "Gerente de Finanzas",
  department: "Finanzas",
  salary: 16000,
  hireDate: "2017-09-25",
  status: "active",
  role: "admin",
},
{
  id: 11,
  name: "Paola Méndez",
  email: "paola.mendez@empresa.com",
  position: "Asistente Administrativa",
  department: "Recursos Humanos",
  salary: 6000,
  hireDate: "2023-01-10",
  status: "active",
  role: "employee",
},
{
  id: 12,
  name: "Javier Ruiz",
  email: "javier.ruiz@empresa.com",
  position: "Ingeniero Backend",
  department: "Tecnologia",
  salary: 11000,
  hireDate: "2019-04-14",
  status: "on_leave",
  role: "employee",
},
{
  id: 13,
  name: "Camila Soto",
  email: "camila.soto@empresa.com",
  position: "Analista Financiera",
  department: "Finanzas",
  salary: 8800,
  hireDate: "2020-08-07",
  status: "active",
  role: "employee",
},
{
  id: 14,
  name: "Diego Herrera",
  email: "diego.herrera@empresa.com",
  position: "Gerente de Proyectos",
  department: "Tecnologia",
  salary: 13500,
  hireDate: "2016-12-01",
  status: "active",
  role: "admin",
},
{
  id: 15,
  name: "Valeria Cruz",
  email: "valeria.cruz@empresa.com",
  position: "Especialista en Nómina",
  department: "Finanzas",
  salary: 7500,
  hireDate: "2021-09-30",
  status: "inactive",
  role: "employee",
},
{
  id: 16,
  name: "Fernando Díaz",
  email: "fernando.diaz@empresa.com",
  position: "Analista de Seguridad",
  department: "Tecnologia",
  salary: 12500,
  hireDate: "2018-03-22",
  status: "active",
  role: "employee",
},
{
  id: 17,
  name: "Gabriela Morales",
  email: "gabriela.morales@empresa.com",
  position: "Psicóloga Organizacional",
  department: "Recursos Humanos",
  salary: 9500,
  hireDate: "2020-06-11",
  status: "active",
  role: "employee",
},
{
  id: 18,
  name: "Ricardo Peña",
  email: "ricardo.pena@empresa.com",
  position: "Auditor Interno",
  department: "Finanzas",
  salary: 10000,
  hireDate: "2019-10-05",
  status: "active",
  role: "employee",
},
{
  id: 19,
  name: "Elena Vargas",
  email: "elena.vargas@empresa.com",
  position: "Especialista en Capacitación",
  department: "Recursos Humanos",
  salary: 7200,
  hireDate: "2022-04-19",
  status: "active",
  role: "employee",
},
{
  id: 20,
  name: "Tomás Navarro",
  email: "tomas.navarro@empresa.com",
  position: "Ingeniero DevOps",
  department: "Tecnologia",
  salary: 14000,
  hireDate: "2017-11-30",
  status: "active",
  role: "employee",
},
{
  id: 21,
  name: "Isabel Flores",
  email: "isabel.flores@empresa.com",
  position: "Analista de Presupuesto",
  department: "Finanzas",
  salary: 8700,
  hireDate: "2021-02-08",
  status: "on_leave",
  role: "employee",
},

    
];